parameters:

services:
    webdevvie_pheanstalktaskqueue.service:
        class: Webdevvie\PheanstalkTaskQueueBundle\Service\TaskQueueService
        arguments:
            - @doctrine.orm.entity_manager
            - @leezy.pheanstalk
            - @jms_serializer
            - %webdevvie_taskqueue.params%

    webdevvie_pheanstalktaskqueue.task_command_generator:
        class: Webdevvie\PheanstalkTaskQueueBundle\Service\TaskCommandGenerator